### PR TITLE
Add >= 1.67.0 to Rust version

### PR DESCRIPTION
**Pull request by charliermarsh**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by charliermarsh** [comment]
@messense - Sorry to bother, do you have any idea how to get this to use Rust 1.67.0? It seems like the `rust-feedback` merged support a long time ago, but it's not resolving here.

**Comment by messense** [comment]
I'm not sure, maybe @pkgw knows?

**Comment by owenlamont** [comment]
I wonder if Rust needs to be added to the Hosts section of the meta.yaml - I'm trying to understand [the docs here](https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html#anaconda-compilers-and-conda-build-3).

I don't have experience with compile steps in conda recipes but I'll see if I can build the recipe locally sometime.

**Comment by felixgwilliams** [comment]
Thanks to all of you for your work on ruff and on making it available on conda-forge!

I saw in the polars feedstock repo there is a file [`conda_build_config.yaml`](https://github.com/conda-forge/polars-feedstock/blob/main/recipe/conda_build_config.yaml) which adds `conda-forge/label/rust_dev` as a channel source.  I believe this might make rust 1.67 available so the recipe can build.

**Comment by charliermarsh** [comment]
Ohh thank you, let me try that...

**Comment by charliermarsh** [comment]
Huzzah, that worked!

**Comment by charliermarsh** [comment]
I'm going to re-open from a fork with a new PR.

**Pull request closed without merging**
